version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antipatterns
  - apache
  - bunzip
  - bzcat
  - bzcmp
  - bzgrep
  - crun
  - dafujii
  - defn
  - drwxr
  - ELIFECYCLE
  - errno
  - Funcs
  - Globex
  - htdocs
  - javac
  - kota
  - kotaoue
  - libapache
  - lrwxrwxrwx
  - myapp
  - myimage
  - myphp
  - myphpimage
  - phpimage
  - rwxr
  - SIGWINCH
  - Stmts
  - VARCHAR
  - webcontent
ignoreWords: []
import: []
