services:
  mysql:
    image: mysql:latest
    container_name: sql_antipatterns_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
